/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarViewContent: typeof import('./components/app/AppBarViewContent.vue')['default']
    AppSidebarContent: typeof import('./components/app/AppSidebarContent.vue')['default']
    AppViewContent: typeof import('./components/app/AppViewContent.vue')['default']
    AuthActions: typeof import('./components/auth/AuthActions.vue')['default']
    AuthActionsButton: typeof import('./components/auth/AuthActionsButton.vue')['default']
    AuthContent: typeof import('./components/auth/AuthContent.vue')['default']
    CategoriesAppBarView: typeof import('./components/views/categories/CategoriesAppBarView.vue')['default']
    CategoriesList: typeof import('./components/listCategories/CategoriesList.vue')['default']
    CategoriesListItemAppBarView: typeof import('./components/listCategories/appBarView/CategoriesListItemAppBarView.vue')['default']
    CategoriesView: typeof import('./components/views/categories/CategoriesView.vue')['default']
    CategoryNotificationDialog: typeof import('./components/categoryNotificationDialog/CategoryNotificationDialog.vue')['default']
    CategoryNotificationListItem: typeof import('./components/categoryNotificationDialog/CategoryNotificationListItem.vue')['default']
    SearchAppBarView: typeof import('./components/views/search/SearchAppBarView.vue')['default']
    SearchView: typeof import('./components/views/search/SearchView.vue')['default']
    SettingsView: typeof import('./components/views/settings/SettingsView.vue')['default']
    StreamList: typeof import('./components/listStream/StreamList.vue')['default']
    StreamListClipsAppBarView: typeof import('./components/listStream/appBarView/StreamListClipsAppBarView.vue')['default']
    StreamListItem: typeof import('./components/listStream/StreamListItem.vue')['default']
    StreamListVideosAppBarView: typeof import('./components/listStream/appBarView/StreamListVideosAppBarView.vue')['default']
    StreamsAppBarView: typeof import('./components/views/streams/StreamsAppBarView.vue')['default']
    StreamsView: typeof import('./components/views/streams/StreamsView.vue')['default']
    ViewContainer: typeof import('./components/viewContainer/ViewContainer.vue')['default']
  }
}
